### ISSUE TITLE
1.Months() does not seams to work as expected

### ISSUE THREAD

**Issue by mgphall** [FluentDateTime/FluentDateTime#10]
If I have a date Jan 1st 1900,  and add one month it returns 31 jan 1900, where I would expect it to return Feb 1st 1900

 regards

**Comment by SimonCropp** [comment]
added

 * `FluentTimeSpan FluentTimeSpan.Add(TimeSpan timeSpan)`
 * `FluentTimeSpan FluentTimeSpan.Subtract(TimeSpan timeSpan)`
 * `DateTimeOffset DateTimeOffsetExtensions.AddFluentTimeSpan(this DateTimeOffset dateTimeOffset, FluentTimeSpan timeSpan)`
 * `DateTimeOffset DateTimeOffsetExtensions.SubtractFluentTimeSpan(this DateTimeOffset dateTimeOffset, FluentTimeSpan timeSpan)`
 * `DateTime DateTimeExtensions.AddFluentTimeSpan(this DateTime dateTime, FluentTimeSpan timeSpan)`
 * `DateTime DateTimeExtensions.SubtractFluentTimeSpan(this DateTime dateTime, FluentTimeSpan timeSpan)`
