### ISSUE TITLE
PreviousYear Has a logic mistake

### ISSUE THREAD

**Issue by dinggeonly** [FluentDateTime/FluentDateTime#106]
public static DateTime PreviousYear(this DateTime start)
        {
            var previousYear = start.Year - 1;
            var numberOfDaysInSameMonthPreviousYear = DateTime.DaysInMonth(previousYear, start.Month);

            if (numberOfDaysInSameMonthPreviousYear < start.Day)
            {
                var differenceInDays = start.Day - numberOfDaysInSameMonthPreviousYear;
                var dateTime = new DateTime(previousYear, start.Month, numberOfDaysInSameMonthPreviousYear, start.Hour, start.Minute, start.Second, start.Millisecond, start.Kind);
                return dateTime - differenceInDays.Days();//I think this is the right logic
                //return dateTime + differenceInDays.Days();
            }
            return new DateTime(previousYear, start.Month, start.Day, start.Hour, start.Minute, start.Second, start.Millisecond, start.Kind);
        }

**Comment by SimonCropp** [comment]
can u share a unit test that illustrates the problem

**Comment by dinggeonly** [comment]
> can u share a unit test that illustrates the problem

Sorry.
I think it's an error in logic, not a bug in code.
So,no unit test is needed.

**Comment by dinggeonly** [comment]
> can u share a unit test that illustrates the problem
I realized that there was a problem.
Both your code and mine, are not absolutely right.
If the input is  [2000-02-29],
the output should be [1999-03-01] or [1999-02-27].
Your logic will get the second one,mine will be the first.
So this is just a scenario worth discussing.

Thanks.
