### ISSUE TITLE
Proposal: DateOnly and TimeOnly support (.NET 6+ only)

### ISSUE THREAD

**Issue by helluvamatt** [FluentDateTime/FluentDateTime#116]
#### Is the feature request related to a problem

This feature would implement support for [DateOnly](https://learn.microsoft.com/en-us/dotnet/api/system.dateonly) and [TimeOnly](https://learn.microsoft.com/en-us/dotnet/api/system.timeonly) for the various fluent methods as appropriate.

`DateOnly` and `TimeOnly` were added in .NET 6 and represent a date and time-of-day respectively. They are both `struct`s, similar to `DateTime`. Notably, they do not include a `Now` or `Today` static property, as `DateTime` does.

#### Describe the solution

Implementing support would need to be done carefully, in order to maintain backwards compatibility with netstandard, .NET 5, and .NET Framework.

1. Multi-target netstandard and net6 - This appears to already be done
2. All implementations need to be gated behind compiler directives for .NET 6+, see [FluentDate.cs#L19](https://github.com/FluentDateTime/FluentDateTime/blob/efa451635f9a2357267b68e490c8f6b30dfd5949/src/FluentDateTime/FluentDate.cs#L19)
3. Decide which `DateTime` extension methods would be applicable to `DateOnly` for `DateOnlyExtensions.cs`
4. Decide which `DateTime` or `TimeSpan` extension methods would be applicable to `TimeOnly` for `TimeOnlyExtensions.cs`
5. Copy and/or implement methods, taking into account available mutation methods on `DateOnly` and `TimeOnly`.
6. Copy and fix all tests for new methods

#### Describe alternatives considered

1. Conversion: Provide methods to convert `DateOnly` to `DateTime` and back. This would be error-prone, and potentially less performant. `DateOnly` is optimized to work at day resolution. Internally, it stores a "day number" which is an offset from some epoch. It could also be error-prone, especially around timezones, when we don't even care about timezones with date (for the most part)
2. Subset: I, personally, only use `DateOnly`. Initial effort would be focused around that, and I find that `TimeOnly` has limited usefulness without a date as well. Most often, if my requirements need a time stored, it is in the form of a timestamp, so I use `DateTime` or `DateTimeOffset`.

#### Additional context

This issue is for discussion of the feature itself. I will be working on the feature myself and will open a pull request at a later date. However, if the maintainers have any feedback or insight that would be helpful to that effort, please comment here.

**Comment by SimonCropp** [comment]
happy to consider a pull request
