### ISSUE TITLE
Update code only nuget package to v1.14.0

### ISSUE THREAD

**Issue by Kobus-Smit** [FluentDateTime/FluentDateTime#17]
Are there any plans to update https://www.nuget.org/packages/FluentDateTime-CodeOnly/ to 1.14?

I see there are only minor changes so it is probably not too important.

![image](https://user-images.githubusercontent.com/11263864/31798844-f467c8b0-b581-11e7-90c6-18142d0bc9df.png)

**Comment by SimonCropp** [comment]
moving forward the code only package will not be maintained.
