### ISSUE TITLE
Set CultureInfo  instead of using CurrentCulture

### ISSUE THREAD

**Issue by Gonzo345** [FluentDateTime/FluentDateTime#74]
#### Is the feature request related to a problem

I'm actually running an AppService on Azure and recently noticed FluentDateTime library is returning unexpected dates. As 
`public static DateTime FirstDayOfWeek(this DateTime dateTime)` method's comment says:

"The beginning of the week is controlled by the current Culture".

Most of my requests are from `es-ES` and Azure runs with `en-US` as default and could not be changed. I could even handle to get the desired CultureInfo with each request, but I can't provide it in any way to FluentDateTime.

#### Describe the solution

Bearing in mind FluentDateTime uses extension methods, would be interesting to offer method overload with a new paramenter which would be the CultureInfo. This would allow to specify the desired culture. Otherwise, it would use the CurrentCulture.

#### Describe alternatives considered

I've considered setting the CurrentCulture with each request but as long as Azure is a managed service, I can't trust this would be something to be kept.

#### Additional context

I previously had my app running on a server which I was able to access and config things such as the language of the OS and so on. With this scenario, I'm almost stuck.

Many thanks in advance.

**Comment by Gonzo345** [comment]
I handled to set the CurrentCulture through `Thread.CurrentThread.CurrentCulture = new System.Globalization.CultureInfo("es-ES");` but it's something I don't really feel comfortable with, so I think this feature would be an interesting addition.

Best regards.

**Comment by SimonCropp** [comment]
happy to accept a pull request that adds an overload with the culture
