### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by jefhtavares** [FluentDateTime/FluentDateTime#8]
Hi, I've implemented 3 new methods in ```DateTime``` and ```DateTimeOffset``` extensions.

```SameDay()``` to determine if two dates are in the same date (day, month and year);
```SameMonth()``` to determine if two dates are in the same month (and year); and
```SameYear()``` to determine if two dates are in the same year

Are you interested in a pull request?

**Comment by SimonCropp** [comment]
sorry for the very delayed response. this is now deployed. i will try to do better in the future
